baseURL = 'https://milanwilliams.github.io/'
languageCode = 'en-us'
title = 'milan williams, home'
theme = 'PaperMod'

[params]
[params.social]
twitter = "@milanwilliamsx"
github = "@milanwilliams"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
