baseURL = 'https://milanwilliams.github.io/'
languageCode = 'en-us'
title = 'milan williams, home'
theme = 'PaperMod'

[params]
[params.social]
twitter = "your_twitter_handle"
github = "your_github_username"